import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { PackagePlus, Search, AlertCircle } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useState } from "react";
import { toast } from "sonner";

export const GestionConsommables = () => {
  const [searchTerm, setSearchTerm] = useState("");

  const { data: consommables = [], isLoading, refetch } = useQuery({
    queryKey: ["consommables"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("produit")
        .select("*")
        .eq("categorie_emballage", 2) // 2 = Consommables (protection individuelle)
        .eq("statut_actif", true)
        .order("reference");
      
      if (error) throw error;
      return data;
    },
  });

  const filteredConsommables = consommables.filter(c => 
    searchTerm === "" || 
    c.reference.toLowerCase().includes(searchTerm.toLowerCase()) ||
    c.nom.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleAjusterStock = async (produitId: string, quantite: number) => {
    try {
      // Créer un mouvement de stock ajustement
      const { error } = await supabase
        .from("mouvement_stock")
        .insert([{
          produit_id: produitId,
          type_mouvement: quantite > 0 ? "ajustement_positif" : "ajustement_negatif",
          quantite: Math.abs(quantite),
          remarques: "Ajustement manuel consommable",
          numero_mouvement: "", // Will be auto-generated by trigger
        }]);

      if (error) throw error;
      toast.success("Stock ajusté");
      refetch();
    } catch (error: any) {
      toast.error("Erreur lors de l'ajustement du stock");
    }
  };

  const alertesStock = consommables.filter(c => c.stock_actuel < c.stock_minimum).length;

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <PackagePlus className="h-5 w-5" />
                Consommables & Protection individuelle
              </CardTitle>
              <CardDescription>
                Gestion des stocks de consommables (cartons, palettes, bacs, EPI)
              </CardDescription>
            </div>
            {alertesStock > 0 && (
              <Badge variant="destructive" className="flex items-center gap-1">
                <AlertCircle className="h-3 w-3" />
                {alertesStock} alerte{alertesStock > 1 ? 's' : ''}
              </Badge>
            )}
          </div>
        </CardHeader>
        <CardContent>
          <div className="mb-4">
            <div className="relative">
              <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
              <Input 
                placeholder="Rechercher un consommable..." 
                className="pl-10"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
          </div>

          {isLoading ? (
            <div className="text-center py-8 text-muted-foreground">Chargement...</div>
          ) : filteredConsommables.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              {searchTerm ? "Aucun consommable trouvé" : "Aucun consommable configuré"}
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Référence</TableHead>
                  <TableHead>Nom</TableHead>
                  <TableHead className="text-center">Stock actuel</TableHead>
                  <TableHead className="text-center">Stock minimum</TableHead>
                  <TableHead className="text-center">Stock maximum</TableHead>
                  <TableHead>Statut</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredConsommables.map((consommable) => {
                  const isAlerte = consommable.stock_actuel < consommable.stock_minimum;
                  const tauxRemplissage = consommable.stock_maximum 
                    ? (consommable.stock_actuel / consommable.stock_maximum) * 100 
                    : 0;

                  return (
                    <TableRow key={consommable.id}>
                      <TableCell className="font-mono text-sm">{consommable.reference}</TableCell>
                      <TableCell className="font-medium">{consommable.nom}</TableCell>
                      <TableCell className="text-center">
                        <span className={isAlerte ? "text-red-600 font-semibold" : ""}>
                          {consommable.stock_actuel}
                        </span>
                      </TableCell>
                      <TableCell className="text-center text-muted-foreground">
                        {consommable.stock_minimum}
                      </TableCell>
                      <TableCell className="text-center text-muted-foreground">
                        {consommable.stock_maximum || "-"}
                      </TableCell>
                      <TableCell>
                        {isAlerte ? (
                          <Badge variant="destructive">Réappro urgent</Badge>
                        ) : tauxRemplissage > 80 ? (
                          <Badge variant="default">Stock OK</Badge>
                        ) : (
                          <Badge variant="secondary">Stock bas</Badge>
                        )}
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-2">
                          <Button 
                            size="sm" 
                            variant="outline"
                            onClick={() => handleAjusterStock(consommable.id, 10)}
                          >
                            +10
                          </Button>
                          <Button 
                            size="sm" 
                            variant="outline"
                            onClick={() => handleAjusterStock(consommable.id, -1)}
                          >
                            -1
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
};